repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      # Python-specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/sbrunner/hooks
    rev: 0.7.0
    hooks:
      # Check that the copyright is up to date
      - id: copyright

  - repo: https://github.com/crate-ci/typos
    rev: v1.17.2
    hooks:
      - id: typos

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    -   id: blackdoc
        additional_dependencies:
        - black==23.10.1

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    - id: mypy
      pass_filenames: false
      args: [--package=pytket.phir, --package=tests]
      additional_dependencies: [
        phir,
        pytest,
        pytket-quantinuum,
        pytket,
        types-setuptools,
      ]
